version: '3.9'

services:

  customers-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=nick
      - POSTGRES_PASSWORD=chapsas
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
